[package]
name = "cerebellum_core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
zmq = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
tokio-tungstenite = { version = "0.21", features = ["rustls-tls-webpki-roots"] }
rustls = { version = "0.22" }
rustls-pki-types = "1.0"
futures-util = "0.3"
hex = "0.4"
url = "2.5"
hmac = "0.12"
sha2 = "0.10"
log = "0.4"
env_logger = "0.10"
dotenv = "0.15"
anyhow = "1.0"
chrono = "=0.4"

ordered-float = "4.2" 
rand = "0.8"  
arrow = "56.0.0"
arrow-array = "56.0.0"
arrow-arith = "56.0.0"
parquet = { version = "56.0.0", features = ["arrow"] }